### ISSUE TITLE
supervisor.services install ModuleNotFoundError: getopt

### ISSUE THREAD

**Issue by madisonleavo** [alexsilva/supervisor#12]
supervisor.services install failing on ModuleNotFoundError: No module named 'getopt' which should be in standard lib.

`Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)] on win32`
`Successfully installed pywin32-227 supervisor-win-4.1.1`
```
C:\Windows\system32>"C:\Program Files (x86)\Python37-32\python.exe" -m supervisor.services install -c C:\Scripts\supervisord.conf
===== command execution failed ====
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\supervisor\services.py", line 249, in <module>
    main()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\supervisor\services.py", line 244, in main
    win32serviceutil.HandleCommandLine(SupervisorService, argv=srv_argv)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\win32\lib\win32serviceutil.py", line 551, in HandleCommandLine
    import getopt
ModuleNotFoundError: No module named 'getopt'

**Comment by madisonleavo** [comment]
Python installation issue! Needed `PYTHONPATH` environment var = `C:\Program Files (x86)\Python37-32`
