### ISSUE TITLE
run as service but cannot stop

### ISSUE THREAD

**Issue by potoo0** [alexsilva/supervisor#9]
I registered supervisor as windows service, but this service cannot be stop.

After click "stop"  in the *figure 1*, I got 1053 error and supervisord still alive.

![image](https://user-images.githubusercontent.com/34411681/71581940-c3246680-2b42-11ea-8c18-e14d503f605c.png)(*figure 1*)

supervisor pyv3.6-service.log:
```
2019-12-30 20:15:54,444 [INFO] supervisor config path: E:\testsv\supervisor\supervisord.conf
2019-12-30 20:15:56,762 [INFO] supervisor starting...
2019-12-30 20:17:44,085 [INFO] supervisorctl shutdown
2019-12-30 20:17:46,113 [ERROR] supervisorctl shutdown execution failed
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\supervisor\services.py", line 137, in SvcStop
    stdout=stdout)
  File "D:\Anaconda3\lib\site-packages\supervisor\supervisorctl.py", line 1433, in main
    sys.exit(c.exitstatus)
SystemExit: 1
```

**Comment by alexsilva** [comment]
Update your version from github to get the fix.

`python -m pip install git+https://github.com/alexsilva/supervisor.git@windows -U`

**Comment by potoo0** [comment]
Not working. 
Actually, I already upgrade to 4.1.1 before this testcase.

**Comment by potoo0** [comment]
em...  After I upgrade from this repo, service raise same error code: 1053. and service still alive in background.

![image](https://user-images.githubusercontent.com/34411681/71585037-28cb1f80-2b50-11ea-8bf1-2a7f76ff41e3.png)

**Comment by alexsilva** [comment]
Can not be the same error.

Did you update with the fix?

`python -m pip install git+https://github.com/alexsilva/supervisor.git@windows -U`

[Fix](https://github.com/alexsilva/supervisor/commit/dac5130c4ed20b123f3e66188e20dfd089e6fe35)

**Comment by potoo0** [comment]
fixed.
 Oh, I forgot reinstall service :), sorry.
